CREATE TABLE IF NOT EXISTS BATCH_JOB_REQUEST (
    JOB_SEQ_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_PARAMETER VARCHAR(200),
    JOB_EXECUTION_ID BIGINT,
    POLLING_STATUS VARCHAR(10) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP
);

